on:
  push: # 每次 push 的时候触发

name: Build Release
jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/') # 只有这次 Commit 是 创建 Tag 时，才进行后续发布操作
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master # checkout 代码
      - uses: actions/setup-go@v2 # 配置 Go 环境
        with:
          go-version: "1.16.4" # 改成自己的版本

      - run: go build -o oss-stinger-linux-amd64 ./oss-stinger.go # 这 3 条是交叉编译 Go 的指令，酌情修改。
      - run: CGO_ENABLED=1 GOOS=windows GOARCH=amd64 go build -o oss-stinger-windows-amd64.exe ./oss-stinger.go
      - run: CGO_ENABLED=1 GOOS=darwin GOARCH=amd64 go build -o oss-stinger-darwin-amd64 ./oss-stinger.go

      - name: Release
        uses: softprops/action-gh-release@v1
        with: # 将下述可执行文件 release 上去
          files: |
            oss-stinger-linux-amd64
            oss-stinger-windows-amd64.exe
            oss-stinger-darwin-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
